### ISSUE TITLE
Feedback for Script directory

### ISSUE THREAD

**Issue by faizan6557** [NeshOfficial/llm.c#1]
Hello Nesh Official !
While runnig this project its showing me error for the foowing input command of script directory :
input_val_bin "dev/data/fineweb10B/fineweb_val_*.bin" \
Kindly if you could suggest

**Comment by Muhammad-Awab** [comment]
Updated the installation steps in the documentation to include specific commands for installing dependencies: `sudo apt-get install -f dependencies.conf`. The code now runs successfully, and all functions execute without errors. Please pull the latest changes, install dependencies, and test. Here ,  this can  resolve your issue.
