### ISSUE TITLE
issue with the get_mujoco_lib_pattern() 

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/llm.c#9]
Hi,

I’ve encountered an issue with the get_mujoco_lib_pattern() and get_external_lib_patterns() functions. It appears that the functions may not correctly handle cases where the platform is not recognized or is unsupported. What changes can we make to ensure that these functions provide appropriate fallback behavior or error messages when the platform is not one of the expected types (Windows, Darwin, or others)?

**Comment by M-Aitisam** [comment]
Hi Aitisam,

To improve the get_mujoco_lib_pattern() and get_external_lib_patterns() functions, you can add default fallback behavior and error handling for unsupported platforms. Here’s an updated version of both functions with these enhancements:


import platform

def get_mujoco_lib_pattern():
    system = platform.system()
    if system == 'Windows':
        return 'mujoco.lib'
    elif system == 'Darwin':
        return 'libmujoco.*.dylib'
    else:
        print(f"Warning: Unsupported platform '{system}' for Mujoco library pattern.")
        return 'libmujoco.so.*'

def get_external_lib_patterns():
    system = platform.system()
    if system == 'Windows':
        return ['mujoco.dll']
    elif system == 'Darwin':
        return ['libmujoco.*.dylib']
    else:
        print(f"Warning: Unsupported platform '{system}' for external library patterns.")
        return ['libmujoco.so.*']

**Comment by Muhammad-Awab** [comment]
Hi Aitisam,

To improve the get_mujoco_lib_pattern() and get_external_lib_patterns() functions, you can add default fallback behavior and error handling for unsupported platforms. Here’s an updated version of both functions with these enhancements:


import platform

def get_mujoco_lib_pattern():
    system = platform.system()
    if system == 'Windows':
        return 'mujoco.lib'
    elif system == 'Darwin':
        return 'libmujoco.*.dylib'
    else:
        print(f"Warning: Unsupported platform '{system}' for Mujoco library pattern.")
        return 'libmujoco.so.*'

def get_external_lib_patterns():
    system = platform.system()
    if system == 'Windows':
        return ['mujoco.dll']
    elif system == 'Darwin':
        return ['libmujoco.*.dylib']
    else:
        print(f"Warning: Unsupported platform '{system}' for external library patterns.")
        return ['libmujoco.so.*']
